config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  resources :images
  # resources :product_images
  # resources :product_categories
  resources :index_images
  resources :products
  resources :categories
  resource :cart, only: [:show] do
    put 'add/:id', to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  # devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # authenticate :user, lambda { |u| u.is_admin == true } do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "pages/template"
  get "pages/index"
  get "pages/login"
  get "index_images" => "index_images#index"
  get "categories/:id" => "categories#show"


  # post 'pages/login' => 'session#create', :as => :user_session
  
  # devise_for :users, controllers: { sessions: 'users/sessions' } do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations" 
    }

end

app/models/product.rb
class Product < ApplicationRecord

    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories
    has_many :product_images, dependent: :destroy
    has_many :images, through: :product_images



    attr_accessor :weight_format


    after_initialize :default_values
    # validates :title, :price, :categories, :description, :images, :weight_type, :weight
    validates :price, numericality: {greater_than: 0}
    
    # validates_format_of :prix
    enum weight_type: {Lbs: "lbs", Kg: "kg"}

    def cart_action(current_user_id)
      if $redis.sismember "cart#{current_user_id}", id
        "Remove from"
      else
        "Add to"
      end
    end

    def default_values
        if self.production_cost.nil?
        self.production_cost = 0
        end
    end

    def weight_format
        [self.weight, self.weight_type].compact.join(' ')
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]
  authorize_resource :class => false
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json

  def index
    time = params[:time]
    # @produxts_for_man = Product.where(:id => params[:sexe])
    @products = Product.where(:created_at => params[:time]... Time.now)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @cart_action = @product.cart_action current_user.try :id
    jsonProduct = @product.to_json
    
    # render json: @product
  end

  # GET /products/new
  def new
    redirect_to rails_admin.new_path('product')
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    redirect_to rails_admin.edit_path('product')

  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Le product a été créer avec succès.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Le product a été modifié avec succès.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Le product a été supprimé avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {})
    end


end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<!-- <%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
-->

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


	<section class="page-header page-header-xs">
		<div class="container">
			<h1>Nouveautés</h1>
			<!-- breadcrumbs -->
			<ol class="breadcrumb">
				<li><%= link_to "Accueil", root_url %></li>
				<li><%= link_to "Retour", :back %></li>
			</ol><!-- /breadcrumbs -->
		</div>
	</section>
			
	<!-- /PAGE HEADER -->
	
	<section>
		<div class="container">
			<ul class="shop-item-list row list-inline m-0">

				<% @products.each do |product| %>
					<!-- ITEM -->
					<li class="col-lg-12" >
						<div class="shop-item clearfix">
							<% if Image.find(product.image_ids).length > 1 %>
								<div class="thumbnail">
									<!-- product image(s) -->
									<%= link_to product_url(id:product.id), :class => "shop-item-image" do %>
										<!-- CAROUSEL -->
										<div class="owl-carousel m-0" data-plugin-options='{"singleItem": true, "autoPlay": 5000, "navigation": false, "pagination": true, "transitionStyle":"fadeUp"}'>
											<%product.images.each do |image|%>
												<img class="img-fluid" src="<%=image.photo%>" alt="">
											<%end%>
										</div>
									<%end%>
									<!-- product more info -->
									<%# <div class="shop-item-info">
										<span class="badge badge-success">NEW</span>
										<span class="badge badge-danger">SALE</span>
									</div> %>
									<!-- /product more info -->
								</div>

							<% else %>
								<div class="thumbnail">
								<!-- product image(s) -->
									<%= link_to product_url(id:product.id), :class => "shop-item-image" do %>
										<div class="m-0">
											<%product.images.each do |image|%>
												<img class="img-fluid" src="<%=image.photo%>" alt="">
											<%end%>
										</div>
									<%end%>
								</div>
							<%end%>
								
							<div class="shop-item-summary">
								<h2><%= product.title %></h2>
									
									<!-- rating -->
									<%# <div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div> %>
									<!-- /rating -->
									
								<p><!-- product short description -->
								<%= product.description %>
								</p><!-- /product short description -->

								<!-- price -->
								<div class="shop-item-price">
									<%# <span class="line-through">$98.00</span> %>
									<%= ActionController::Base.helpers.number_to_currency(product.price)  %> CAD 
								</div>
								<!-- /price -->

								<!-- buttons -->
								<div class="shop-item-buttons">
									<a class="btn btn-light" href=""><i class="fa fa-cart-plus"></i> Ajouter au panier </a>
									<!-- replace data-item-id width the real item ID - used by js/view/demo.shop.js -->
									<%# <a class="btn btn-light add-wishlist" href="#" data-item-id="1" data-toggle="tooltip" title="Add To Wishlist"><i class="fa fa-heart p-0"></i></a> %>
								</div>
								<!-- /buttons -->
							</div>
						</div>
					</li>
					<!-- /ITEM -->

              	<% end %>
			</ul>
			<hr />
			<!-- Pagination Default -->
			<%# <div class="text-center">
				<ul class="pagination">
					<li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
					<li class="page-item active"><a class="page-link" href="#">1</a></li>
					<li class="page-item"><a class="page-link" href="#">2</a></li>
					<li class="page-item"><a class="page-link" href="#">3</a></li>
					<li class="page-item"><a class="page-link" href="#">4</a></li>
					<li class="page-item"><a class="page-link" href="#">5</a></li>
					<li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
				</ul>
			</div> %>
			<!-- /Pagination Default -->
					
		</div>
	</section>
	<%= render :partial => 'layouts/footer' %>


   

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
	<section class="page-header page-header-xs">
		<div class="container">
			<h1><%= @product.title %></h1>
			<!-- breadcrumbs -->
			<ol class="breadcrumb">
				<li><%= link_to "Home", root_url %></li>
				<li><%= link_to "Back", :back %></li>
			</ol><!-- /breadcrumbs -->
		</div>
	</section>

			<section>
				<div class="container">
					<div class="row">

						<!-- IMAGE -->
						<div class="col-lg-4 col-sm-4">
							<div class="thumbnail relative mb-3">
								<!-- 
									IMAGE ZOOM 
									data-mode="mouseover|grab|click|toggle"
								-->
								<figure id="zoom-primary" class="zoom" data-mode="mouseover">
									<% if @product.images.first %>
									<a class="lightbox bottom-right" href="<%= @product.images.first.photo%>" data-plugin-options='{"type":"image"}'><i class="fa fa-search"></i></a>
									<img class="img-fluid" src="<%= @product.images.first.photo%>" width="1200" height="1500" alt="<%= @product.title %>" />
								</figure>
									<% end %>
							</div>

							<!-- Thumbnails (required height:100px) -->
						<% if @product.images.first %>							

							<div data-for="zoom-primary" class="zoom-more owl-carousel owl-padding-3 featured" data-plugin-options='{"singleItem": false, "autoPlay": false, "navigation": true, "pagination": false}'>
								<a class="thumbnail active" href="<%= @product.images.first.photo %>">
									<img src="<%= @product.images.first.photo %>" height="100" alt="" />
								</a>

								<% @product.images.each do |image| %>
									<% if image != @product.images.first %>								
								<a class="thumbnail" href="<%= image.photo %>">
									<img src="<%= image.photo %>" height="100" alt="" />
								</a>
								<%end%>
								<%end%>
							</div>
								<%end%>

							<!-- /Thumbnails -->

						</div>
						<!-- /IMAGE -->


						<!-- ITEM DESC -->
						<div class="col-lg-5 col-sm-8">
							<!-- buttons -->
							<div class="float-right">
							</div>
							<!-- /buttons -->
							<!-- price -->
							<div class="shop-item-price">
								<%= ActionController::Base.helpers.number_to_currency(@product.price) %> CAD
							</div>
							<!-- /price -->
							<hr />

							<div class="clearfix mb-30">
							<% if @product.instance_variable_defined?(:@total_quantity) && @product.total_quantity > 0 %>
								<span class="float-right text-success"><i class="fa fa-check"></i> Available </span>
								<% else %>
								<span class="float-right text-danger"><i class="fa fa-remove"></i> Unavailable </span>
								<%end%>
							</div>
							<!-- short description -->
							<p><%= @product.description %>! </p>
							<hr />

							<!-- FORM -->
							<%= form_for @product do |f| %>
							<form class="clearfix form-inline m-0" method="get" action="">
								<input type="hidden" name="product_id" value="<%= @product.id %>" />
								<!-- see assets/js/view/demo.shop.js -->


								<div class="btn-group float-left product-opt-qty">

									</select> 
								</div>
								
								
								<!-- /btn-group -->
								<%if signed_in?%>
									  <%=link_to '', class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@product), removeUrl: remove_from_cart_path(@product)} do%>
									    <span><%=@cart_action%></span> Cart
									  <%end%>
									<%end %>
								<%end%>
							</form>
							<!-- /FORM -->
							<hr/>
						</div>
						<!-- /ITEM DESC -->

						<!-- INFO -->
						<%# <div class="col-sm-4 col-md-3"> %>
							
							<%# Shipping method, maybe  %>

							<%# <h4 class="fs-18"> %>
								<%# <i class="fa fa-paper-plane-o"></i>  %>
								<%# FREE SHIPPING %>
							<%# </h4> %>
							<%# <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas metus nulla.</p> %>
							

							<%# Warranty? %>

							<%# <h4 class="fs-18"> %>
								<%# <i class="fa fa-clock-o"></i> %>
								<%# 30 DAYS MONEY BACK %>
							<%# </h4> %>
							<%# <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas metus nulla.</p> %>

							
						<!-- /INFO -->

					</div>

					<!-- RELATED -->
					<%# <h2 class="owl-featured"><strong>Related</strong> products:</h2>
					<div class="owl-carousel featured m-0 owl-padding-10" data-plugin-options='{"singleItem": false, "items": "5", "stopOnHover":false, "autoPlay":4500, "autoHeight": false, "navigation": true, "pagination": false}'>

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p13.jpg" alt="shop first image" />
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p14.jpg" alt="shop hover image" />
								</a>
								<!-- /product image(s) -->

								<!-- product more info -->
								<div class="shop-item-info">
									<span class="badge badge-success">NEW</span>
									<span class="badge badge-danger">SALE</span>
								</div>
								<!-- /product more info -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Cotton 100% - Pink Shirt</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									<span class="line-through">$98.00</span>
									$78.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div>
						<!-- /item -->

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<!-- CAROUSEL -->
									<div class="owl-carousel owl-padding-0 m-0" data-plugin-options='{"singleItem": true, "autoPlay": 3000, "navigation": false, "pagination": false, "transitionStyle":"fadeUp"}'>
										<img class="img-fluid" src="demo_files/images/shop/products/300x450/p5.jpg" alt="">
										<img class="img-fluid" src="demo_files/images/shop/products/300x450/p1.jpg" alt="">
									</div>
									<!-- /CAROUSEL -->
								</a>
								<!-- /product image(s) -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Pink Dress 100% Cotton</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									$44.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div>
						<!-- /item -->

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p2.jpg" alt="shop first image" />
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p12.jpg" alt="shop hover image" />
								</a>
								<!-- /product image(s) -->

								<!-- product more info -->
								<div class="shop-item-info">
									<span class="badge badge-success">NEW</span>
									<span class="badge badge-danger">SALE</span>
								</div>
								<!-- /product more info -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Black Fashion Hat</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									<span class="line-through">$77.00</span>
									$65.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div>
						<!-- /item -->

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p8.jpg" alt="shop first image" />
								</a>
								<!-- /product image(s) -->

								<!-- countdown -->
								<div class="shop-item-counter">
									<div class="countdown" data-from="December 31, 2020 08:22:01" data-labels="years,months,weeks,days,hour,min,sec"><!-- Example Date From: December 31, 2018 15:03:26 --></div>
								</div>
								<!-- /countdown -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Beach Black Lady Suit</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									$56.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div>
						<!-- /item -->

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p7.jpg" alt="shop first image" />
								</a>
								<!-- /product image(s) -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Town Dress - Black</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									$154.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div>
						<!-- /item -->

						<!-- item -->
						<div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p6.jpg" alt="shop first image" />
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p14.jpg" alt="shop hover image" />
								</a>
								<!-- /product image(s) -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Chick Lady Fashion</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-4 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									$167.00
								</div>
								<!-- /price -->
							</div>

								<%# <!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div> %>
						<!-- /item -->

						<!-- item -->
						<%# <div class="shop-item m-0">

							<div class="thumbnail">
								<!-- product image(s) -->
								<a class="shop-item-image" href="shop-single-left.html">
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p11.jpg" alt="shop hover image" />
									<img class="img-fluid" src="demo_files/images/shop/products/300x450/p3.jpg" alt="shop first image" />
								</a>
								<!-- /product image(s) -->
							</div>
							
							<div class="shop-item-summary text-center">
								<h2>Black Long Lady Shirt</h2>
								
								<!-- rating -->
								<div class="shop-item-rating-line">
									<div class="rating rating-0 fs-13"><!-- rating-0 ... rating-5 --></div>
								</div>
								<!-- /rating -->

								<!-- price -->
								<div class="shop-item-price">
									$128.00
								</div>
								<!-- /price -->
							</div>

								<!-- buttons -->
								<div class="shop-item-buttons text-center">
									<a class="btn btn-light" href="shop-cart.html"><i class="fa fa-cart-plus"></i> Add to Cart</a>
								</div>
								<!-- /buttons -->
						</div> %>
						<!-- /item -->

					<%# </div> %> 
					<!-- /RELATED -->

				</div>
			</section>
			<!-- / -->
		<%= render :partial => 'layouts/footer' %>
			