config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  resources :images
  # resources :product_images
  # resources :product_categories
  resources :index_images
  resources :products
  resources :categories
  resource :cart, only: [:show] do
    put 'add/:id', to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  # devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # authenticate :user, lambda { |u| u.is_admin == true } do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "pages/template"
  get "pages/index"
  get "pages/login"
  get "index_images" => "index_images#index"
  get "categories/:id" => "categories#show"


  # post 'pages/login' => 'session#create', :as => :user_session
  
  # devise_for :users, controllers: { sessions: 'users/sessions' } do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations" 
    }

end

app/models/image.rb
class Image < ApplicationRecord
    has_many :product_images
    has_many :products, through: :product_images

    mount_uploader :photo , ImageProductUploader
    validates :photo, presence: true

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  authorize_resource :class => false

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    redirect_to rails_admin.new_path('Image')
    # @image = Image.new
  end

  # GET /images/1/edit
  def edit
    redirect_to rails_admin.edit_path('Image')
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'L\'image a été détruit avec succès.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.fetch(:image, {})
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>