config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  resources :images
  # resources :product_images
  # resources :product_categories
  resources :index_images
  resources :products
  resources :categories
  resource :cart, only: [:show] do
    put 'add/:id', to: 'carts#add', as: :add_to
    put 'remove/:id', to: 'carts#remove', as: :remove_from
  end

  # devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  # authenticate :user, lambda { |u| u.is_admin == true } do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#index"
  get "pages/template"
  get "pages/index"
  get "pages/login"
  get "index_images" => "index_images#index"
  get "categories/:id" => "categories#show"


  # post 'pages/login' => 'session#create', :as => :user_session
  
  # devise_for :users, controllers: { sessions: 'users/sessions' } do
    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations" 
    }

end

app/views/layouts/_footer.html.erb
						<!-- GOOTER -->
			<footer id="footer" class="footer-fixed opacity-9">
				<div class="container mb-0 p-0 clearfix fs-12">

					<!-- Social Icons -->
					<div class="clearfix float-left mobile-block text-center">

						<a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/alexandra.derepentigny.3/posts/2816996885185747" class="social-icon social-icon-sm social-icon-border social-facebook float-left" data-toggle="tooltip" data-placement="top" title="Facebook">
							<i class="icon-facebook"></i>
							<i class="icon-facebook"></i>
						</a>

						<span class="float-left footer-links hidden-xs-down">
							<span><%= ENV['CONTACT_US_PHONE'] %></span>
							<a href="#">Contact</a>
							<a href="#">FAQ</a>
							<a href="#">Cart (0)</a> 
						</span>
					</div>
					<!-- /Social Icons -->
					
					<span class="hidden-xs-down fs-13 line-h-30 float-right">
						&copy; <script>
            					  var CurrentYear = new Date().getFullYear()
            					  document.write(CurrentYear)
        					   </script> <%= ENV["WEB_APP_NAME"] %>. All Rights Reserved.
					</span>
				</div>
			</footer>
	    <!-- /FOOTER -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV["WEB_APP_NAME"] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <head lang="fr">
    <meta charset="utf-8" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
     
  </head>

	<body class="smoothscroll enable-animation">
    <!-- Loading animation --> 
		<%# <!-- PRELOADER --> %>
		<div id="preloader">
			<div class="inner">
				<span class="loader"></span>
			</div>
		</div><!-- /PRELOADER --> 

    <!-- ALERT -->
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
	  <script> 
	  
	  </script>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <!-- /ALERT -->
    <script>var  plugin_path = '/assets/plugins/';</script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%# Header %>
  <div id="header" class="navbar-toggleable-md sticky clearfix">

				<!-- TOP NAV -->
				<header id="topNav">
					<div class="container">
  
						<!-- Logo -->
						<a class="logo float-left" href="<%root_url%>">
						<%# Logo height : 96px  %>
							<%# <img src="assets/images/_smarty/logo_light.png" alt="" /> %> 
						</a>
						<div class="navbar-collapse collapse float-right nav-main-collapse ">
							<nav class="nav-main">
								<ul id="topMain" class="nav nav-pills nav-main">
								<li class="dropdown">
									<a class="dropdown-toggle"> New items </a>
									<ul class="dropdown-menu">

									<!-- Items created within a week -->
									<% if Product && Category %>
									<% time = 1.week.ago %>
									<% new_products = Product.where(:created_at => time...Time.now).order('created_at DESC')%>
									<% new_products.each do |products|%>
										<li><%= link_to products.title, product_path(products.id) %> </li>
										<%end%>
										<li><%= link_to "All our new items", products_path(time: time) %> </li>
										<%else%>
										<li> Items coming soon !</li>
										<%end%>
									</ul>
								</li>
								<!--  Categories below -->
								<%# <li class="dropdown">
									<a class="dropdown-toggle" href="#"> Men </a>
									<ul class="dropdown-menu">
									</ul>

								</li>
								<li class="dropdown">
									<a class="dropdown-toggle"> Women </a>
									<ul class="dropdown-menu">

									</ul>
									

								</li> %>
								<%# if User is logged_in  %>

								<% if current_user %>
									<li class="dropdown">
										<a class="dropdown-toggle">My account</a>
										<ul class="dropdown-menu">
                          					<li> <%= link_to 'Edit my account', edit_user_registration_path  %> </li> 
                          					<li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
											  	<li><%= link_to cart_path do%>
									   				 My Cart
									   				(<span class="cart-count"><%=current_user.cart_count%></span>)
												</li>
									  <%end%>
									</li>
										</ul>
									</li>

								<% else %>

									<li><%= link_to 'Login', pages_login_url %></li>

								<%end%>

								<%# If admin is logged_in %>
								<% if current_user &&  current_user.is_admin? %>
									<li><a href="/admin"> Admin </a></li>
								<% end %>
                  </div>
                </div>
              </div>
    <%= yield %>
    
  </body>
</html>